name             'apache2'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures apache2'
long_description 'Installs/Configures apache2'
version          '0.1.0'
